# Generated by Django 3.2 on 2024-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0003_auto_20230129_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='captcha_requirement',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Only for reCaptcha v3: Minimum score required to accept challenge.', max_digits=3, verbose_name='Minimum score requirement'),
        ),
        migrations.AlterField(
            model_name='form',
            name='captcha_widget',
            field=models.CharField(blank=True, choices=[('', '-----'), ('v2-checkbox', 'reCaptcha - v2 checkbox'), ('v2-invisible', 'reCaptcha - v2 invisible')], default='v2-invisible', help_text='Read more in the <a href="https://developers.google.com/recaptcha" target="_blank">documentation</a>.', max_length=16, verbose_name='captcha widget'),
        ),
    ]
