# Generated by Django 3.2 on 2024-02-20 18:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0004_auto_20240220_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
