# Generated by Django 3.2 on 2024-02-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0005_auto_20240220_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormProxy',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_form_builder.form',),
        ),
    ]
