# Generated by Django 3.2 on 2024-02-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0003_auto_20240220_0235'),
        ('djangocms_form_builder', '0006_formproxy'),
    ]

    operations = [
    ]
